### ISSUE TITLE
issue with the default.js

### ISSUE THREAD

**Issue by UnrealValentin** [Satoqz/dnd-api#1]
when you try to call the Equipment Class you get the following error:
`(node:6524) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at C:\Users\valen\Desktop\Discord-Bot-Template-2-master\node_modules\dnd-api\build\routes\default.js:22:66
    at Array.filter (<anonymous>)
    at Function.<anonymous> (C:\Users\valen\Desktop\Discord-Bot-Template-2-master\node_modules\dnd-api\build\routes\default.js:22:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\valen\Desktop\Discord-Bot-Template-2-master\node_modules\dnd-api\build\routes\default.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
fix pls

**Comment by UnrealValentin** [comment]
Code that threw the error: `/* eslint-disable no-underscore-dangle */
/* eslint-disable require-jsdoc */
const { Command } = require('discord-akairo');
const equipment = require("dnd-api").StarterEquip;

class EquipmentCommand extends Command {
    constructor() {
        super('equipment', {
            aliases: [ 'equipment', 'equip' ],
            category: 'wiki',
            ownerOnly: false,
            channel: '',
            typing: false,
            editable: true,
            cooldown: 0,
            userPermissions: [],
            clientPermissions: [ 'SEND_MESSAGES' ],
            args: [
                {
                    id: 'msg',
                    type: 'string',
					match: 'content',
					default: null,
                }
            ],
            description: {
                content: [
                    'Search for equipment',
                ],
                usage: '[equipment]',
                examples: [ 'equip' ],
            }
        });
    }

    async exec(message, args) {

        if (!args.msg) return message.util.send('```;equip [name]```');

        if (message.author.bot) {
            return message.util.send("A bot can't use this.");
        }
        const response = await equipment.get(args.msg);
        if (response.error) {
            const search = await equipment.list(args.msg);
            let desc;

            desc = "```";

            search.results.forEach((e) => {
                if (desc !== null) {
                    desc += ` - ${e.name}\n`;
                } else {
                    desc = `\`\`\` - ${e}\n`;
                }
            });

            desc += "```";
            const embed = this.client.util.embed()
            .setColor(this.client.config.color)
            .setFooter(`Get Wiki Card with ;equip [name]`)
            .setTitle(`Equipment Search`)
            .setDescription(desc);
            return message.util.send({ embed });

        }
        /*
        let actions = "";
        let abilities = "";

        console.log(_keys(response));

        response.classes.forEach((e) => {
            actions += `\n - ${e.name}`;
        });

        response.subclasses.forEach((e) => {
            abilities += `\n - ${e.name}`;
        });

        const embed = this.client.util.embed()
            .setColor(this.client.config.color)
            .setFooter(`Get Wiki Card with ;equip [name]`)
            .setTitle(`Equipment: ${args.msg}`)
            .setDescription([ `Name: ${response.name}`, `Description: ${response.desc}`, `Higher Levels: ${response.higher_level}`, `Range: ${response.range}`, `Components: ${response.components}`, `Material: ${response.material}`, `Ritual: ${response.ritual}`, `Duration: ${response.duration}`, `Needs concentration: ${response.concentration}`, `Casting time: ${response.casting_time}`, `Level: ${response.level}`, `School: ${response.school.name}`, `Classes: ${actions}`, `Subclasses: ${abilities}` ]);
            const fulldesc = embed.description;
            for (let i = 0; i < fulldesc.length; i += 2000) {
                const toSend = fulldesc.substring(i, Math.min(fulldesc.length, i + 2000));
                embed.setDescription(`\`\`\`${toSend}\`\`\`` );
                message.util.send({ embed });
            }
            return message.react("👍");
            */

    }
}

function isObject(obj) {
    const type = typeof obj;
    return type === 'function' || type === 'object' && Boolean(obj);
  }

function _keys(obj) {
    if (!isObject(obj)) return [];
    if (Object.keys) return Object.keys(obj);
    const keys = [];
    for (const key in obj) if (_.has(obj, key)) keys.push(key);
    return keys;
  }

module.exports = EquipmentCommand;`

**Comment by UnrealValentin** [comment]
This works tho: `    async exec(message, args) {

        if (!args.msg) return message.util.send('```;spell [name]```');

        if (message.author.bot) {
            return message.util.send("A bot can't use this.");
        }
        const response = await spells.get(args.msg);
        if (response.error) {
            const search = await spells.list(args.msg);
            let desc;

            desc = "```";

            search.results.forEach((e) => {
                if (desc !== null) {
                    desc += ` - ${e.name}\n`;
                } else {
                    desc = `\`\`\` - ${e}\n`;
                }
            });

            desc += "```";
            const embed = this.client.util.embed()
            .setColor(this.client.config.color)
            .setFooter(`Get Wiki Card with ;spell [name]`)
            .setTitle(`Spell Search`)
            .setDescription(desc);
            return message.util.send({ embed });

        }
        let actions = "";
        let abilities = "";

        response.classes.forEach((e) => {
            actions += `\n - ${e.name}`;
        });

        response.subclasses.forEach((e) => {
            abilities += `\n - ${e.name}`;
        });

        const embed = this.client.util.embed()
            .setColor(this.client.config.color)
            .setFooter(`Get Wiki Card with ;Spell [name]`)
            .setTitle(`Spell: ${args.msg}`)
            .setDescription([ `Name: ${response.name}`, `Description: ${response.desc}`, `Higher Levels: ${response.higher_level}`, `Range: ${response.range}`, `Components: ${response.components}`, `Material: ${response.material}`, `Ritual: ${response.ritual}`, `Duration: ${response.duration}`, `Needs concentration: ${response.concentration}`, `Casting time: ${response.casting_time}`, `Level: ${response.level}`, `School: ${response.school.name}`, `Classes: ${actions}`, `Subclasses: ${abilities}` ]);
            const fulldesc = embed.description;
            for (let i = 0; i < fulldesc.length; i += 2000) {
                const toSend = fulldesc.substring(i, Math.min(fulldesc.length, i + 2000));
                embed.setDescription(`\`\`\`${toSend}\`\`\`` );
                message.util.send({ embed });
            }
            return message.react("👍");

    }`

**Comment by TheDevMinerTV** [comment]
Found the issue ^^

**Comment by UnrealValentin** [comment]
fixed it
